/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nexus.java.gui;

import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import nexus.java.business.AnimalBo;
import nexus.java.entity.Animal;

/**
 *
 * @author MaruLanD
 */
public class AnimalAddUpdateForm extends javax.swing.JFrame {

    private AnimalBo animalBo = AnimalBo.getInstance();
    private boolean ifAdd = true;

    Animal animal = new Animal();

    public AnimalAddUpdateForm() {
        initComponents();
        jTFIdAnimal.setText((animalBo.getMaxID() + 1) + "");

    }

    public AnimalAddUpdateForm(int id) {

        animal = animalBo.readByID(id);

        initComponents();
        jTFIdAnimal.setText(animal.getIdAnimal() + "");
        jTFAge.setText(animal.getAge() + "");
        jTextArea1.setText(animal.getCommentaire());
        jTFCouleur.setText(animal.getCouleur());
        jTFEspece.setText(animal.getEspece());
        if (animal.getSexe().equals("Male")) {
            jRBMal.setSelected(true);
        } else {
            jRBFem.setSelected(true);
        }
        jTFTaille.setText(animal.getTaille());
        jCBType.setSelectedItem(animal.getType());

        ifAdd = false;
        jBAdd.setText("Modifier");
        titre.setText("Modifier un animal");

        ImageIcon ima = new ImageIcon(animal.getImage().getAbsolutePath());

        jLabel2.setIcon(ima);
        jLabel2.setSize(100, 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        BGSexe = new javax.swing.ButtonGroup();
        JImage = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTFIdAnimal = new javax.swing.JTextField();
        jTFEspece = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFCouleur = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTFTaille = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jRBFem = new javax.swing.JRadioButton();
        jRBMal = new javax.swing.JRadioButton();
        jTFAge = new javax.swing.JTextField();
        jBImg = new javax.swing.JButton();
        jCBType = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jBCancel = new javax.swing.JButton();
        jBAdd = new javax.swing.JButton();
        titre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jUrl = new javax.swing.JTextField();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        BGSexe.add(jRBFem);
        BGSexe.add(jRBMal);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("icon.jpg")).getImage());
        setResizable(false);

        JImage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Id de l'animal: ");
        JImage.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jTFIdAnimal.setBackground(new java.awt.Color(250, 250, 250));
        jTFIdAnimal.setEnabled(false);
        JImage.add(jTFIdAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 164, -1));
        JImage.add(jTFEspece, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 164, -1));

        jLabel6.setText("Espece: ");
        JImage.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel7.setText("Couleur: ");
        JImage.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 57, 10));
        JImage.add(jTFCouleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 164, -1));

        jLabel8.setText("Type: ");
        JImage.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel9.setText("Taille: ");
        JImage.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));
        JImage.add(jTFTaille, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 164, -1));

        jLabel10.setText("Age: ");
        JImage.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 114, -1, 20));

        jLabel11.setText("Image: ");
        JImage.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 40, 20));

        jLabel12.setText("Sexe: ");
        JImage.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 30, 10));

        jRBFem.setText("Female");
        JImage.add(jRBFem, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 60, 30));

        jRBMal.setText("Male");
        jRBMal.setSelected(true);
        JImage.add(jRBMal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 50, 30));

        jTFAge.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFAgeFocusLost(evt);
            }
        });
        JImage.add(jTFAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 110, 150, -1));

        jBImg.setText("Parcourir");
        jBImg.setPreferredSize(new java.awt.Dimension(75, 20));
        jBImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImgActionPerformed(evt);
            }
        });
        JImage.add(jBImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 80, 20));

        jCBType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chien", "Chat", "Hamster", "Oiseau", "Singe", "autre" }));
        JImage.add(jCBType, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 164, -1));

        jLabel13.setText("Commentaire:");
        JImage.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 70, 10));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        JImage.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 150, 120));

        jBCancel.setText("Annuler");
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });
        JImage.add(jBCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 80, 20));

        jBAdd.setText("Ajouter");
        jBAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddActionPerformed(evt);
            }
        });
        JImage.add(jBAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 80, 20));

        titre.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        titre.setText("Ajouter un animal");
        JImage.add(titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));
        JImage.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));
        JImage.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jUrl.setText("URL de l'image");
        JImage.add(jUrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JImage, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JImage, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        this.setVisible(false);
        new MainAnimalForm().setVisible(true);
    }//GEN-LAST:event_jBCancelActionPerformed

    private void jBAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddActionPerformed
        animal.setAge(Integer.parseInt(jTFAge.getText()));
        animal.setCommentaire(jTextArea1.getText());
        animal.setCouleur(jTFCouleur.getText());
        animal.setEspece(jTFEspece.getText());
        if (jRBMal.isSelected()) {
            animal.setSexe("Male");
        } else {
            animal.setSexe("Female");
        }
        animal.setTaille(jTFTaille.getText());
        animal.setType(jCBType.getSelectedItem().toString());

        String errors = animalBo.verifAnimal(animal) + "\n" + animalBo.verifAnimal(animal);
        if (errors != null) {
            if (ifAdd) {
                animalBo.insert(animal);
                this.setVisible(false);
                new MainAnimalForm().setVisible(true);
            } else {
                animalBo.update(animal);
                this.setVisible(false);
                new MainAnimalForm().setVisible(true);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Veuillez revérifier les champs suivants: \n" + errors, "Erreur", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jBAddActionPerformed

    private void jTFAgeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFAgeFocusLost
        try {
            if (jTFAge.getText() != null) {
                Integer.parseInt(jTFAge.getText());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Vous ne pouvez saisir que des chiffres", "Age", JOptionPane.ERROR_MESSAGE);
            jTFAge.setText("");
        }
    }//GEN-LAST:event_jTFAgeFocusLost

    private void jBImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImgActionPerformed

        try {
            JFileChooser picchooser = new JFileChooser();
            int returnval = picchooser.showOpenDialog(null);
            File file = null;
            if (returnval == JFileChooser.APPROVE_OPTION) {
                file = picchooser.getSelectedFile();
                String filename = file.getAbsolutePath();
                // File pics = new File(filename);
                ImageIcon ima = new ImageIcon(filename);
                //FileInputStream fistream1 = new FileInputStream (pics);
                animal.setImage(file);
                jLabel2.setIcon(ima);
                jLabel2.setSize(100, 100);
                jUrl.setText(filename);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
// pas de fichier choisi

// TODO add your handling code here:
    }//GEN-LAST:event_jBImgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnimalAddUpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnimalAddUpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnimalAddUpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnimalAddUpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimalAddUpdateForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGSexe;
    private javax.swing.JPanel JImage;
    private javax.swing.JButton jBAdd;
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBImg;
    private javax.swing.JComboBox jCBType;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRBFem;
    private javax.swing.JRadioButton jRBMal;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFAge;
    private javax.swing.JTextField jTFCouleur;
    private javax.swing.JTextField jTFEspece;
    private javax.swing.JTextField jTFIdAnimal;
    private javax.swing.JTextField jTFTaille;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jUrl;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
