/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nexus.java.gui;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import nexus.java.business.AnimalBo;
import nexus.java.business.DeclarationBo;
import nexus.java.business.MembreBo;
import nexus.java.entity.Animal;
import nexus.java.entity.Declaration;
import nexus.java.entity.Membre;

/**
 *
 * @author MaruLanD
 */
public class DeclarationAddUpdateForm extends javax.swing.JFrame {

    private DeclarationBo declarationBo = DeclarationBo.getInstance();
    private AnimalBo animalBo = AnimalBo.getInstance();
    private MembreBo membreBo = MembreBo.getInstance();
    private boolean ifAdd = true;

    Animal animal = new Animal();
    Declaration declaration = new Declaration();
    Membre membre = new Membre();

    public DeclarationAddUpdateForm() {
        initComponents();
        jTFIdAnimal.setText((animalBo.getMaxID() + 1) + "");
        jTFIdRec.setText((declarationBo.getMaxID() + 1) + "");
        //jTFIdRec.setText((declarationBo.getMaxID() + 1) + "");

    }

    public DeclarationAddUpdateForm(int id) {

        declaration = declarationBo.readByID(id);
        animal = declaration.getAnimal();
        membre = declaration.getMembre();

        initComponents();
        jTFIdAnimal.setText(animal.getIdAnimal() + "");
        jTFAge.setText(animal.getAge() + "");
        jTextArea1.setText(animal.getCommentaire());
        jTFCouleur.setText(animal.getCouleur());
        jTFEspece.setText(animal.getEspece());
        if (animal.getSexe().equals("Male")) {
            jRBMal.setSelected(true);
        } else {
            jRBFem.setSelected(true);
        }
        jTFTaille.setText(animal.getTaille());
        jCBType.setSelectedItem(animal.getType());
        jTFIdRec.setText(declaration.getIdDeclaration() + "");
        jTAComm.setText(declaration.getCommentaire());
        jTFEtat.setText(declaration.getEtat());
        jTFLieux.setText(declaration.getLieuDeclaration());
        jXDPDate.setDate(declaration.getDate());
        

        ifAdd = false;
        jBAdd.setText("Modifier");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        BGSexe = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFLieux = new javax.swing.JTextField();
        jTFEtat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAComm = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jTFIdAnimal = new javax.swing.JTextField();
        jTFEspece = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFCouleur = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTFTaille = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jRBFem = new javax.swing.JRadioButton();
        jRBMal = new javax.swing.JRadioButton();
        jTFAge = new javax.swing.JTextField();
        jBImg = new javax.swing.JButton();
        jCBType = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTFIdRec = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jBCancel = new javax.swing.JButton();
        jBAdd = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jXDPDate = new org.jdesktop.swingx.JXDatePicker();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        BGSexe.add(jRBFem);
        BGSexe.add(jRBMal);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("icon.jpg")).getImage());
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Lieux de l'animal: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, -1));

        jLabel2.setText("Etat de l'animal:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 76, -1, -1));

        jLabel3.setText("Commentaire:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 133, -1, -1));
        jPanel1.add(jTFLieux, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 165, -1));
        jPanel1.add(jTFEtat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 165, -1));

        jTAComm.setColumns(14);
        jTAComm.setRows(5);
        jScrollPane1.setViewportView(jTAComm);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 146, 165, -1));

        jLabel4.setText("Id de l'animal: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 14, -1, -1));

        jTFIdAnimal.setBackground(new java.awt.Color(250, 250, 250));
        jTFIdAnimal.setEnabled(false);
        jPanel1.add(jTFIdAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 11, 164, -1));
        jPanel1.add(jTFEspece, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 42, 164, -1));

        jLabel6.setText("Espece: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 45, -1, -1));

        jLabel7.setText("Couleur: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 76, 57, 10));
        jPanel1.add(jTFCouleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 71, 164, -1));

        jLabel8.setText("Type: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 124, -1, -1));

        jLabel9.setText("Taille: ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 146, -1, -1));
        jPanel1.add(jTFTaille, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 135, 164, -1));

        jLabel10.setText("Age: ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 177, -1, -1));

        jLabel11.setText("Image: ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 200, -1, -1));

        jLabel12.setText("Sexe: ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 228, -1, -1));

        jRBFem.setText("Female");
        jPanel1.add(jRBFem, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 224, -1, -1));

        jRBMal.setText("Male");
        jRBMal.setSelected(true);
        jPanel1.add(jRBMal, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 224, -1, -1));

        jTFAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFAgeActionPerformed(evt);
            }
        });
        jTFAge.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFAgeFocusLost(evt);
            }
        });
        jPanel1.add(jTFAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 166, 164, -1));

        jBImg.setText("Parcourir");
        jBImg.setPreferredSize(new java.awt.Dimension(75, 20));
        jPanel1.add(jBImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 197, 164, -1));

        jCBType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jCBType, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 104, 164, -1));

        jLabel5.setText("Id: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jTFIdRec.setBackground(new java.awt.Color(250, 250, 250));
        jTFIdRec.setEnabled(false);
        jPanel1.add(jTFIdRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 165, -1));

        jLabel13.setText("Commentaire:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 254, -1, -1));

        jTextArea1.setColumns(14);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 254, -1, -1));

        jBCancel.setText("Annuler");
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jBCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 361, -1, -1));

        jBAdd.setText("Ajouter");
        jBAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddActionPerformed(evt);
            }
        });
        jPanel1.add(jBAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 361, -1, -1));

        jLabel14.setText("Date :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 108, -1, -1));
        jPanel1.add(jXDPDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 108, 165, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        this.setVisible(false);
        new MainDeclarationForm().setVisible(true);
    }//GEN-LAST:event_jBCancelActionPerformed

    private void jBAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddActionPerformed
        try {
            animal.setAge(Integer.parseInt(jTFAge.getText()));
        } catch (NumberFormatException ex) {
        }
        animal.setCommentaire(jTextArea1.getText());
        animal.setCouleur(jTFCouleur.getText());
        animal.setEspece(jTFEspece.getText());
        if (jRBMal.isSelected()) {
            animal.setSexe("Male");
        } else {
            animal.setSexe("Female");
        }
        animal.setTaille(jTFTaille.getText());
        animal.setType(jCBType.getSelectedItem().toString());
        declaration.setCommentaire(jTAComm.getText());
        declaration.setEtat(jTFEtat.getText());
        declaration.setLieuDeclaration(jTFLieux.getText());
        declaration.setType((short) 1);
        declaration.setDate(jXDPDate.getDate());

        String errors = animalBo.verifAnimal(animal) + declarationBo.verifDeclaration(declaration);
        if (errors.equals("")) {
            if (ifAdd) {
                declarationBo.insert(declaration, animal);
                this.setVisible(false);
                new MainDeclarationForm().setVisible(true);
            } else {
                declarationBo.update(declaration, animal);
                this.setVisible(false);
                new MainDeclarationForm().setVisible(true);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Veuillez revérifier les champs suivants: \n" + errors, "Erreur", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jBAddActionPerformed

    private void jTFAgeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFAgeFocusLost
        try {
            if (jTFAge.getText() != null) {
                Integer.parseInt(jTFAge.getText());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Vous ne pouvez saisir que des chiffres", "Age", JOptionPane.ERROR_MESSAGE);
            jTFAge.setText("");
        }
    }//GEN-LAST:event_jTFAgeFocusLost

    private void jTFAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFAgeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeclarationAddUpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeclarationAddUpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeclarationAddUpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeclarationAddUpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeclarationAddUpdateForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGSexe;
    private javax.swing.JButton jBAdd;
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBImg;
    private javax.swing.JComboBox jCBType;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBFem;
    private javax.swing.JRadioButton jRBMal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTAComm;
    private javax.swing.JTextField jTFAge;
    private javax.swing.JTextField jTFCouleur;
    private javax.swing.JTextField jTFEspece;
    private javax.swing.JTextField jTFEtat;
    private javax.swing.JTextField jTFIdAnimal;
    private javax.swing.JTextField jTFIdRec;
    private javax.swing.JTextField jTFLieux;
    private javax.swing.JTextField jTFTaille;
    private javax.swing.JTextArea jTextArea1;
    private org.jdesktop.swingx.JXDatePicker jXDPDate;
    // End of variables declaration//GEN-END:variables
}
